//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

namespace PiStellwerk.Data.Migrations
{
    public partial class MutliImageSupport : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ImageFileName",
                table: "Engines");

            migrationBuilder.CreateTable(
                name: "Engineimages",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Filename = table.Column<string>(type: "TEXT", nullable: true),
                    IsGenerated = table.Column<bool>(type: "INTEGER", nullable: false),
                    Width = table.Column<int>(type: "INTEGER", nullable: false),
                    EngineId = table.Column<int>(type: "INTEGER", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Engineimages", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Engineimages_Engines_EngineId",
                        column: x => x.EngineId,
                        principalTable: "Engines",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Engineimages_EngineId",
                table: "Engineimages",
                column: "EngineId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Engineimages");

            migrationBuilder.AddColumn<string>(
                name: "ImageFileName",
                table: "Engines",
                type: "TEXT",
                nullable: true);
        }
    }
}
