// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

namespace TauStellwerk.Database.Migrations
{
    public partial class AdditionalIndices : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_Engines_Created",
                table: "Engines",
                column: "Created");

            migrationBuilder.CreateIndex(
                name: "IX_Engines_LastUsed",
                table: "Engines",
                column: "LastUsed");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Engines_Created",
                table: "Engines");

            migrationBuilder.DropIndex(
                name: "IX_Engines_LastUsed",
                table: "Engines");
        }
    }
}
